---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/21 19:55
---

local aoe = {};
aoe.Model = require("Designer/Aoe_Model");
aoe.OnTick = require("Designer/Aoe_OnTick");
return aoe;