---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/8/6 15:43
---

local GameLuaInterface = CS.TheGame.GM.GameLuaInterface;
local DamageInfoTag = CS.MBF.DamageInfoTag;
local CharacterState = CS.MBF.CharacterState;

local aoe_onRemove = {};

aoe_onRemove.MineExplode = function(aoeState)
    local targetCharacters = GameLuaInterface.GetTargetsInRange(aoeState.transform.position, aoeState.side, true, false, aoeState.model.onRemoveParams[0]);

    -- TODO: Can modify damage here
    local baseAtk = 100;
    for i, cs in pairs(targetCharacters) do
        if (_G.Utils.IsNil(cs) or cs:GetComponent(typeof(CharacterState)).IsDead or cs.side == aoeState.side) then
            goto continue;
        end

        GameLuaInterface.CreateDamage(aoeState.caster, cs.gameObject, { bullet = baseAtk * cs.grade }, { DamageInfoTag.DirectHurt });
        :: continue ::
    end

    GameLuaInterface.CreateSightEffect(
            aoeState.model.prefab .. "_Hit",
            aoeState.transform.position
    );
end

aoe_onRemove.SpikeEffect = function(aoeState)
    local radius = aoeState.model.onRemoveParams[0];
    local addBuffInfo = aoeState.model.onRemoveParams[1];
    -- TODO: Can modify control time here
    addBuffInfo.duration = 250;
    local targetCharacters = GameLuaInterface.GetTargetsInRange(aoeState.transform.position, aoeState.side, true, false, radius);
    for i, cs in pairs(targetCharacters) do
        if (_G.Utils.IsNil(cs) or cs:GetComponent(typeof(CharacterState)).IsDead or cs.side == aoeState.side) then
            goto continue;
        end

        --GameLuaInterface.CreateDamage(aoeState.caster, cs.gameObject, { bullet = aoeState.propWhileCast.atk }, { DamageInfoTag.DirectHurt });
        cs:AddBuff(addBuffInfo);
        :: continue ::
    end

    --GameLuaInterface.CreateSightEffect(
    --        aoeState.model.prefab .. "_Hit",
    --        aoeState.transform.position
    --);
end

return aoe_onRemove;