---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/5/8 14:38
---

local GameLuaInterface = CS.TheGame.GM.GameLuaInterface;
local DamageInfoTag = CS.MBF.DamageInfoTag;
local CharacterState = CS.MBF.CharacterState;

local aoe_onTick = {};

aoe_onTick.Shandian = function(aoeState)
    for i, cs in pairs(aoeState.charactersInRange) do
        if (Utils.IsNil(cs) or cs:GetComponent(typeof(CharacterState)).IsDead or cs.side == aoeState.side) then
            goto continue;
        end

        GameLuaInterface.CreateDamage(aoeState.caster, cs.gameObject, { bullet = aoeState.propWhileCast.atk }, { DamageInfoTag.DirectHurt });

        GameLuaInterface.CreateSightEffect(
                aoeState.model.prefab .. "_Hit",
                cs.transform.position
        );

        ::continue::
    end
end

return aoe_onTick;