---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/5/8 14:36
---

local AddBuffInfo = CS.MBF.AddBuffInfo;

local aoe_onTick = require("Designer/Aoe_OnTick");
local aoe_onCharacterEnter = require("Designer/Aoe_OnCharacterEnter");
local aoe_onRemove = require("Designer/Aoe_OnRemove");
local buffTable = require("Designer/Buff");

local aoe_model = {
    aoe_shandian = {
        id = "aoe_shandian",
        prefab = "AoeThunderSword",
        onTick = aoe_onTick["Shandian"],
        onTickParams = nil,
        onCreate = nil,
        onCreateParams = nil,
        onRemove = nil,
        onRemoveParams = nil,
        onCharacterEnter = nil,
        onCharacterEnterParams = nil,
        onCharacterLeave = nil,
        onCharacterLeaveParams = nil
    },
    aoe_mine = {
        id = "aoe_mine",
        prefab = "AoeMine",
        onTick = nil,
        onTickParams = nil,
        onCreate = nil,
        onCreateParams = nil,
        onRemove = aoe_onRemove["MineExplode"],
        onRemoveParams = { 3 }, -- 爆炸半径
        onCharacterEnter = aoe_onCharacterEnter["TriggerMine"],
        onCharacterEnterParams = { 75 }, -- 倒计时帧数
        onCharacterLeave = nil,
        onCharacterLeaveParams = nil
    },
    aoe_spike = {
        id = "aoe_spike",
        prefab = "AoeSpike",
        onTick = nil,
        onTickParams = nil,
        onCreate = nil,
        onCreateParams = nil,
        onRemove = aoe_onRemove["SpikeEffect"],
        onRemoveParams = { 3, AddBuffInfo(
                buffTable["buff_stun"], -- model
                nil, -- caster
                50, -- duration
                false -- permanent
        ) }, -- 爆炸半径
        onCharacterEnter = aoe_onCharacterEnter["TriggerSpike"],
        onCharacterEnterParams = { 75 }, -- 倒计时帧数
        onCharacterLeave = nil,
        onCharacterLeaveParams = nil
    },
};

return aoe_model;