---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 17:24
---

local ChaProp = CS.MBF.ChaProp;
local ChaControlState = CS.MBF.ChaControlState;

local buff = {};

buff.buff_stun = {
    id = "buff_stun",
    tags = {},
    propMod = {
        ChaProp.zero,
        ChaProp.zero,
    },
    stateMod = ChaControlState.stun,
};


return buff;