---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/25 15:54
---

local Vector3 = CS.UnityEngine.Vector3;
local Time = CS.UnityEngine.Time;
local Mathf = CS.UnityEngine.Mathf;

local tween = {};

tween.StraightTween = function(t, bs, target)
    return bs.launchDir * bs.speed * CS.UnityEngine.Time.fixedDeltaTime;
end

tween.StraightFollowTween = function(t, bs, target)
    if (Utils.IsNil(bs.followingTarget) or bs.followingTarget:GetComponent(typeof(CS.MBF.CharacterState)).IsDead or (not bs:CanHit(bs.followingTarget))) then
        return tween.StraightTween(t, bs, target);
    end
    --local targetPos = Vector3.MoveTowards(bs.transform.position, bs.targetPos, bs.speed * Time.fixedDeltaTime);
    bs.targetPos = bs.followingTarget.transform.position;
    local targetDir = (bs.targetPos - bs.transform.position).normalized;
    bs.transform.right = targetDir;
    return targetDir * bs.speed * Time.fixedDeltaTime;
end

local ArrowTween = function(t, bs, target, upMultiplier, vDirSign)
    if (not Utils.IsNil(bs.followingTarget)) then
        bs.targetPos = bs.followingTarget.transform.position;
    end

    local function TickPos(t, bs, target)
        local targetVec = bs.targetPos - bs.launchPos;
        local targetDir = targetVec.normalized;
        local percentage = Mathf.Min(1, bs.speed * t * Time.fixedDeltaTime / targetVec.magnitude);
        local nextPos = Vector3.Lerp(bs.launchPos, bs.targetPos, percentage);

        local offsetDir = Vector3(-targetDir.y, targetDir.x);
        if (Vector3.Dot(Vector3(-targetDir.y, targetDir.x), Vector3.up) < 0) then
            offsetDir = Vector3(-targetDir.y, targetDir.x) * -1;
        end

        local upOffset = offsetDir * vDirSign * upMultiplier * Mathf.Sin(Mathf.PI * percentage);
        nextPos = nextPos + upOffset;
        return nextPos;
    end

    local nextPos = TickPos(t, bs, target);
    local nextNextPos = TickPos(t + 0.1, bs, target);
    local dir = (TickPos(t + 1, bs, target) - nextPos).normalized;

    local goVec = (nextPos - bs.transform.position);
    if (nextPos ~= nextNextPos) then
        bs.transform.right = dir;
    end

    bs:SetPos(nextPos);
    return Vector3.zero;
end

tween.ArrowStraightTween = function(t, bs, target)
    return ArrowTween(t, bs, target, 0, 1);
end

tween.ArrowUpTween = function(t, bs, target)
    return ArrowTween(t, bs, target, 0.2, 1);
end

tween.InstantTween = function(t, bs, target)
    if (not Utils.IsNil(bs.followingTarget)) then
        bs:SetPos(bs.followingTarget.transform.position);
    end
    return Vector3.zero;
end

return tween;