---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 20:02
---

local targeting = {};
targeting.GetNearestEnemy = function(bs, targets)
    return CS.TheGame.GM.GameLuaInterface.GetNearestTarget(
            bs.gameObject,
            bs.side,
            bs.model.hitFoe,
            bs.model.hitAlly,
            bs.caster:GetComponent(typeof(CS.MBF.CharacterState)).Prop.rng
    );
end

targeting.GetCurrentTarget = function(bs, targets)
    return bs.caster:GetComponent(typeof(CS.TheGame.ITargetHolder)):GetTarget();
end

return targeting;