---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/25 11:21
---

local MBF = CS.MBF;
local CharacterState = MBF.CharacterState;
local ChaResType = MBF.ChaResType;
local GameLuaInterface = CS.TheGame.GM.GameLuaInterface;
local DamageInfoTag = MBF.DamageInfoTag;
local Damage = MBF.Damage;
local AoeLauncher = MBF.AoeLauncher;
local aoe = require("Designer/Aoe")

local onHit = {};

onHit.CommonBulletHit = function(bs, target)
    local cs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(cs) or cs.IsDead) then
        return;
    end

    GameLuaInterface.CreateDamage(
        bs.caster.gameObject,
        target,
        { bullet = bs.propWhileCast.atk },
        { DamageInfoTag.DirectHurt }
    );

    GameLuaInterface.CreateSightEffect(
        bs.model.prefab .. "_Hit",
        cs.transform.position
    );
end

onHit.CommonAoeBulletHit = function(bs, target)
    local cs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(cs) or cs.IsDead) then
        return;
    end

    GameLuaInterface.CreateDamage(
        bs.caster.gameObject,
        target,
        { bullet = math.ceil(bs.propWhileCast.atk * 0.5) },
        { DamageInfoTag.DirectHurt }
    );

    GameLuaInterface.CreateSightEffect(
        bs.model.prefab .. "_Hit",
        cs.transform.position
    );
end

onHit.CommonBulletHealHit = function(bs, target)
    local cs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(cs) or cs.IsDead) then
        return;
    end

    GameLuaInterface.CreateDamage(
        bs.caster.gameObject,
        target,
        { bullet = -bs.propWhileCast.atk },
        { DamageInfoTag.DirectHeal }
    );

    GameLuaInterface.CreateSightEffect(
        bs.model.prefab .. "_Hit",
        cs.transform.position
    );
end

onHit.CommonBulletRisingHit = function(bs, target)
    local targetCs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(targetCs) or targetCs.IsDead) then
        return;
    end
    local casterCs = bs.caster:GetComponent(typeof(CharacterState));
    local casterOriginSpeed = 0;
    if (not _G.Utils.IsNil(casterCs) and not casterCs.IsDead) then
        casterOriginSpeed = casterCs.resource.speed;
        targetCs:SetResource(ChaResType.Speed, targetCs.resource.speed + casterOriginSpeed);
        casterCs:SetResource(ChaResType.Speed, 0);
        GameLuaInterface.CreateSightEffect(
            bs.model.prefab .. "_Hit",
            targetCs.transform.position
        );
    end
end

onHit.CreateAoeOnHit = function(bs, target)
    local al = bs.model.onHitParams[0];
    al.caster = bs.caster;
    al.side = bs.side;
    al.targetPos = target.transform.position;
    al.propWhileCast = bs.propWhileCast;
    GameLuaInterface.CreateAoe(al);
end

return onHit;
