---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 20:03
---

local AoeLauncher = CS.MBF.AoeLauncher;
local ChaProp = CS.MBF.ChaProp;
local Vector3 = CS.UnityEngine.Vector3;

local aoeTable = require("Designer/Aoe");
local bullet_onHit = require("Designer/Bullet_OnHit")

local model = {
    bullet_guanyu = {
        id = "bullet_guanyu",
        prefab = "BulletFireBall",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_zhangfei = {
        id = "bullet_zhangfei",
        prefab = "BulletPurpleSword",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_machao = {
        id = "bullet_machao",
        prefab = "BulletTiger",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_huangzhong = {
        id = "bullet_huangzhong",
        prefab = "BulletIceArrow",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_zhugeliang = {
        id = "bullet_zhugeliang",
        prefab = "BulletThunderSword",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CreateAoeOnHit"],
        onHitParams = {
            -- model, caster, side, targetPos, duration, tickTime, radius, propWhileCast, parameters
            AoeLauncher(aoeTable.Model["aoe_shandian"], nil, -1, Vector3.zero, 2, 1, 2.0, ChaProp.zero, nil)
        }
    },
    bullet_a = {
        id = "bullet_a",
        prefab = "Bullet斩击",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_arrow = {
        id = "bullet_arrow",
        prefab = "BulletArrow",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_fire_arrow = {
        id = "bullet_fire_arrow",
        prefab = "Bullet火箭",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_qianghua = {
        id = "bullet_qianghua",
        prefab = "Bullet枪划",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_heal = {
        id = "bullet_heal",
        prefab = "Bullet治疗",
        hitFoe = false,
        hitAlly = true,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHealHit"],
        onHitParams = {}
    },
    bullet_rising = {
        id = "bullet_rising",
        prefab = "Bullet鼓舞",
        hitFoe = false,
        hitAlly = true,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletRisingHit"],
        onHitParams = {}
    },
    bullet_qinglong = {
        id = "bullet_qinglong",
        prefab = "Bullet青龙旋风斩",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_fire_strike = {
        id = "bullet_fire_strike",
        prefab = "Bullet火攻",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
    bullet_dongfeng = {
        id = "bullet_dongfeng",
        prefab = "Bullet东风",
        hitFoe = true,
        hitAlly = false,
        sameTargetDelay = 50,
        onHit = bullet_onHit["CommonBulletHit"],
        onHitParams = {}
    },
};

return model;
