---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/21 19:43
---

--- {
---     public string id;
---     public string prefab;
---     public bool hitFoe;
---     public bool hitAlly;
---     public int sameTargetDelay;
---     public BulletOnHit onHit;
---     public object[] onHitParams;
--- }


local bullet = {};
bullet.Model = require("Designer/Bullet_Model");
bullet.Targeting = require("Designer/Bullet_Targeting");
bullet.OnHit = require("Designer/Bullet_OnHit");
bullet.Tween = require("Designer/Bullet_Tween");
return bullet;