---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/25 11:21
---

local MBF = CS.MBF;
local CharacterState = MBF.CharacterState;
local ChaResType = MBF.ChaResType;
local GameLuaInterface = CS.TheGame.GM.GameLuaInterface;
local DamageInfoTag = MBF.DamageInfoTag;
local Damage = MBF.Damage;
local AoeLauncher = MBF.AoeLauncher;
local aoe = require("Designer/Aoe")

local onHit = {};

onHit.CommonBulletHit = function(bs, target)
    local cs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(cs) or cs.IsDead) then
        return;
    end

    GameLuaInterface.CreateDamage(
        bs.caster.gameObject,
        target,
        { bullet = bs.propWhileCast.atk },
        { DamageInfoTag.DirectHurt }
    );

    GameLuaInterface.CreateSightEffect(
        bs.model.prefab .. "_Hit",
        cs.transform.position
    );
end

onHit.CommonBulletHealHit = function(bs, target)
    local cs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(cs) or cs.IsDead) then
        return;
    end

    GameLuaInterface.CreateDamage(
        bs.caster.gameObject,
        target,
        { bullet = -bs.propWhileCast.atk },
        { DamageInfoTag.DirectHeal }
    );

    GameLuaInterface.CreateSightEffect(
        bs.model.prefab .. "_Hit",
        cs.transform.position
    );
end

onHit.CommonBulletRisingHit = function(bs, target)
    local cs = target:GetComponent(typeof(CharacterState));
    if (Utils.IsNil(cs) or cs.IsDead) then
        return;
    end

    cs:SetResource(ChaResType.Speed, cs.Prop.speed + bs.propWhileCast.atk);
    local caster = bs.caster:GetComponent(typeof(CharacterState));
    if (cs == caster and not _G.Utils.IsNil(caster) and not caster.IsDead) then
        caster:SetResource(ChaResType.Speed, 0);
    end

    GameLuaInterface.CreateSightEffect(
        bs.model.prefab .. "_Hit",
        cs.transform.position
    );
end

onHit.CreateAoeOnHit = function(bs, target)
    local al = bs.model.onHitParams[0];
    al.caster = bs.caster;
    al.side = bs.side;
    al.targetPos = target.transform.position;
    al.propWhileCast = bs.propWhileCast;
    GameLuaInterface.CreateAoe(al);
end

return onHit;
