---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 17:20
---

local ChaProp = CS.MBF.ChaProp;
local CharacterType = CS.TheGame.GM.CharacterType;
local Rarity = CS.TheGame.GM.Rarity;

local des = require("Designer/Character_Description");

--- Id, Name, Tags, Description, Prefab, SkillIds, BaseProp, PropGrowth
local character = {
    -- PlayerActor
    {
        Id = "cha_liubei",
        Name = "刘备",
        Tags = { "default", "playerActor", },
        CharacterType = CharacterType.Support,
        Rarity = Rarity.Rare,
        Description = des["刘备"],
        Prefab = "刘备",
        SkillIds = { "skill_liubei" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(12, 36, 0, 0, 12), ChaProp.zero }
    },
    {
        Id = "cha_guanyu",
        Name = "关羽",
        Tags = { "default", "playerActor" },
        CharacterType = CharacterType.Warrior,
        Rarity = Rarity.Rare,
        Description = des["关羽"],
        Prefab = "关羽",
        SkillIds = { "skill_guanyu" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(24, 13, 0, 0, 13), ChaProp.zero }
    },
    {
        Id = "cha_zhangfei",
        Name = "张飞",
        Tags = { "default", "playerActor" },
        CharacterType = CharacterType.Tank,
        Rarity = Rarity.Rare,
        Description = des["张飞"],
        Prefab = "张飞",
        SkillIds = { "skill_zhangfei" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(36, 12, 0, 0, 12), ChaProp.zero }
    },
    {
        Id = "cha_zhaoyun",
        Name = "赵云",
        Tags = { "playerActor", },
        CharacterType = CharacterType.Assassin,
        Rarity = Rarity.Rare,
        Description = des["赵云"],
        Prefab = "赵云",
        SkillIds = { "skill_zhaoyun" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(12, 24, 0, 0, 24), ChaProp.zero }
    },
    {
        Id = "cha_zhugeliang",
        Name = "诸葛亮",
        Tags = { "playerActor" },
        CharacterType = CharacterType.Carry,
        Rarity = Rarity.SuperRare,
        Description = des["诸葛亮"],
        Prefab = "诸葛亮",
        SkillIds = { "skill_zhugeliang" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(14, 42, 20, 10, 14), ChaProp.zero }
    },
    {
        Id = "cha_pangtong",
        Name = "庞统",
        Tags = { "playerActor" },
        CharacterType = CharacterType.Carry,
        Rarity = Rarity.Rare,
        Description = des["庞统"],
        Prefab = "庞统",
        SkillIds = { "skill_pangtong" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(12, 24, 0, 0, 12), ChaProp.zero }
    },
    {
        Id = "cha_sunquan",
        Name = "孙权",
        Tags = { "playerActor" },
        CharacterType = CharacterType.Support,
        Rarity = Rarity.Rare,
        Description = des["孙权"],
        Prefab = "孙权",
        SkillIds = { "skill_sunquan" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(12, 24, 0, 0, 12), ChaProp.zero }
    },
    {
        Id = "cha_zhouyu",
        Name = "周瑜",
        Tags = { "playerActor" },
        CharacterType = CharacterType.Carry,
        Rarity = Rarity.SuperRare,
        Description = des["周瑜"],
        Prefab = "周瑜",
        SkillIds = { "skill_zhouyu" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(14, 42, 20, 10, 14), ChaProp.zero }
    },
    {
        Id = "cha_xiahoudun",
        Name = "夏侯惇",
        Tags = { "playerActor" },
        CharacterType = CharacterType.Tank,
        Rarity = Rarity.Normal,
        Description = des["夏侯惇"],
        Prefab = "夏侯惇",
        SkillIds = { "skill_xiahoudun" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(30, 10, 0, 0, 10), ChaProp.zero }
    },
    {
        Id = "cha_lvbu",
        Name = "吕布",
        Tags = { "playerActor" },
        CharacterType = CharacterType.Warrior,
        Rarity = Rarity.Legendary,
        Description = des["吕布"],
        Prefab = "吕布",
        SkillIds = { "skill_lvbu" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(32, 24, 0, 0, 24), ChaProp.zero }
    },

    -- Soldier
    {
        Id = "cha_bubing",
        Name = "步兵小兵",
        Tags = {},
        CharacterType = CharacterType.Warrior,
        Rarity = Rarity.Normal,
        Description = nil,
        Prefab = "步兵小兵",
        SkillIds = { "skill_bubing" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(20, 15, 0, 0, 15), ChaProp.zero }
    },
    {
        Id = "cha_qishou",
        Name = "旗手",
        Tags = {},
        CharacterType = CharacterType.Support,
        Rarity = Rarity.Normal,
        Description = nil,
        Prefab = "旗手",
        SkillIds = { "skill_qishou" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(10, 30, 0, 0, 10), ChaProp.zero }
    },
    {
        Id = "cha_gongbing",
        Name = "三国弓兵",
        Tags = {},
        CharacterType = CharacterType.Carry,
        Rarity = Rarity.Normal,
        Description = nil,
        Prefab = "三国弓兵",
        SkillIds = { "skill_gongbing" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(10, 30, 0, 0, 10), ChaProp.zero }
    },
    {
        Id = "cha_gushou",
        Name = "鼓手",
        Tags = {},
        CharacterType = CharacterType.Support,
        Rarity = Rarity.Normal,
        Description = nil,
        Prefab = "鼓手",
        SkillIds = { "skill_gushou" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(10, 30, 0, 0, 10), ChaProp.zero }
    },
    {
        Id = "cha_shuibing",
        Name = "水兵",
        Tags = {},
        CharacterType = CharacterType.Assassin,
        Rarity = Rarity.Normal,
        Description = nil,
        Prefab = "吴国水兵",
        SkillIds = { "skill_shuibing" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(10, 20, 0, 0, 20), ChaProp.zero }
    },
    {
        Id = "cha_huwei",
        Name = "重装护卫",
        Tags = {},
        CharacterType = CharacterType.Tank,
        Rarity = Rarity.Rare,
        Description = nil,
        Prefab = "重装护卫",
        SkillIds = { "skill_huwei" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(30, 10, 0, 0, 10), ChaProp.zero }
    },
    {
        Id = "cha_qibing",
        Name = "骑兵",
        Tags = {},
        CharacterType = CharacterType.Assassin,
        Rarity = Rarity.Rare,
        Description = nil,
        Prefab = "骑兵",
        SkillIds = { "skill_qibing" },
        --- hp, atk, rng, skillSpd, speed
        BaseProp = ChaProp(500, 100, 0, 0, 100),
        PropGrowth = { ChaProp(10, 20, 0, 0, 20), ChaProp.zero }
    },
};

return character;
