---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Danny.
--- DateTime: 2025/4/30 0:57
---


local character_description = {
    { "cha_zhaoyun", "【赵云】字子龙，白马银枪，英姿飒爽，被誉为“常胜将军”，蜀汉五虎上将之一。" },
    { "cha_lvbu", "【吕布】字奉先，纵马挺戟时有「人中吕布，马中赤兔」之威。方天画戟横扫千军。" },
};

local dict = {};

for i, v in pairs(character_description) do
    dict[v[1]] = v[2];
end

return dict;