---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Danny.
--- DateTime: 2025/4/30 0:57
---


local character_description = {
    { "cha_zhaoyun", "【赵云】字子龙，白马银枪，英姿飒爽，被誉为“常胜将军”，蜀汉五虎上将之一。" },
    { "cha_lvbu", "【吕布】字奉先，纵马挺戟时有「人中吕布，马中赤兔」之威。方天画戟横扫千军。" },
    { "cha_pangtong", "【庞统】号凤雏，相貌丑陋却胸怀韬略，献连环计火烧赤壁，助刘备取西川时身先士卒，终殒命落凤坡，堪称天妒奇才。" },
    { "cha_sunquan", "【孙权】字仲谋，碧目紫髯，年少继业坐镇江东，善权衡制衡，赤壁鏖战、江东开发，成就“生子当如孙仲谋”霸业。" },
};

local dict = {};

for i, v in pairs(character_description) do
    dict[v[1]] = v[2];
end

return dict;