---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/29 19:43
---

local fieldIndexDes = {};
fieldIndexDes.Id = 1;
fieldIndexDes.Des = 2;

local equipment_description = {};

local mtDes = {};
mtDes.__index = function(table, key)
    if (fieldIndexDes[key]) then
        return table[fieldIndexDes[key]];
    end
end
mtDes.__metatable = false;

for _, v in pairs(equipment_description) do
    setmetatable(v, mtDes);
end

local description_dict = {};
for _, v in pairs(equipment_description) do
    description_dict[v.Id] = v.Des;
end

return description_dict;