---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/25 16:39
---
local MBF = CS.MBF;
local EquipmentSlot = MBF.EquipmentSlot;
-- hp, atk, rng, skillSpd, moveSpd
local ChaProp = MBF.ChaProp;

local equipment = {};
-- id, tags, slot, propMod, addBuffs
equipment["item_equipment_雷神之杖"] = { id = "item_equipment_雷神之杖", name = "雷神之杖", tags = nil, description = "", slot = EquipmentSlot.Weapon, propMod = { ChaProp(0, 50, 10, 20, 0), ChaProp.zero }, addBuffs = nil };
equipment["item_equipment_奇幻军刀"] = { id = "item_equipment_奇幻军刀", name = "奇幻军刀", tags = nil, description = "", slot = EquipmentSlot.Weapon, propMod = { ChaProp(0, 100, 0, 0, 0), ChaProp.zero }, addBuffs = nil };
equipment["item_equipment_奇幻战甲"] = { id = "item_equipment_奇幻战甲", name = "奇幻战甲", tags = nil, description = "", slot = EquipmentSlot.Armor, propMod = { ChaProp(100, 20, 0, 0, 0), ChaProp.zero }, addBuffs = nil };
equipment["item_equipment_奇幻战盔"] = { id = "item_equipment_奇幻战盔", name = "奇幻战盔", tags = nil, description = "", slot = EquipmentSlot.Helmet, propMod = { ChaProp(100, 20, 0, 0, 0), ChaProp.zero }, addBuffs = nil };
equipment["item_equipment_奇幻战靴"] = { id = "item_equipment_奇幻战靴", name = "奇幻战靴", tags = nil, description = "", slot = EquipmentSlot.Shoe, propMod = { ChaProp(100, 20, 0, 0, 0), ChaProp.zero }, addBuffs = nil };
equipment["item_equipment_奇幻之心"] = { id = "item_equipment_奇幻之心", name = "奇幻之心", tags = nil, description = "", slot = EquipmentSlot.Relic, propMod = { ChaProp(0, 0, 100, 200, 0), ChaProp.zero }, addBuffs = nil };
equipment["item_equipment_高能电池"] = { id = "item_equipment_高能电池", name = "高能电池", tags = nil, description = "", slot = EquipmentSlot.Relic, propMod = { ChaProp(0, 0, 200, 100, 0), ChaProp.zero }, addBuffs = nil };
--{ id = "item_equipment_雷霆战盔", name = "雷霆战盔", tags = nil, description = "", slot = EquipmentSlot.Helmet, propMod = { ChaProp(100, 20, 0, 0, 0), ChaProp.zero }, addBuffs = nil },
--{ id = "item_equipment_雷霆战甲", name = "雷霆战甲", tags = nil, description = "", slot = EquipmentSlot.Armor, propMod = { ChaProp(100, 20, 0, 0, 0), ChaProp.zero }, addBuffs = nil },
--{ id = "item_equipment_雷霆战靴", name = "雷霆战靴", tags = nil, description = "", slot = EquipmentSlot.Shoe, propMod = { ChaProp(100, 20, 0, 0, 0), ChaProp.zero }, addBuffs = nil },

return equipment;