---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/21 19:53
---

local formula = {};

formula.GetMoveSpeed = function(moveSpeed)
    return moveSpeed * 0.01;
end

formula.GetSkillSpeed = function(skillSpeed)
    return skillSpeed * 0.01;
end

formula.GetDamage = function(damageInfo)
    return damageInfo.damage.bullet;
end

formula.GetRange = function(range)
    return range * 0.01;
end

return formula;