---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/25 15:53
---

local ItemType = CS.TheGame.ItemType;

local equip_des = require("Designer/Equipment_Description");

local fieldIndex = {};
fieldIndex.Id = 1;
fieldIndex.Name = 2;
fieldIndex.Type = 3;
fieldIndex.Description = 4;

local item = {
    -- Id, Name, ItemType, Description

    -- Currency 0 --
    { "item_currency_coin", "金币", ItemType.Currency, "基础货币。" },
    { "item_currency_crystal", "水晶", ItemType.Currency, "高级货币，用于购买高级商品。" },

    -- Equipment 1 --
    { "item_equipment_雷神之杖", "雷神之杖", ItemType.Equipment, "" },
    { "item_equipment_奇幻军刀", "奇幻军刀", ItemType.Equipment, "" },
    { "item_equipment_奇幻战甲", "奇幻战甲", ItemType.Equipment, "" },
    { "item_equipment_奇幻战盔", "奇幻战盔", ItemType.Equipment, "" },
    { "item_equipment_奇幻战靴", "奇幻战靴", ItemType.Equipment, "" },
    { "item_equipment_奇幻之心", "奇幻之心", ItemType.Equipment, "" },
    { "item_equipment_高能电池", "高能电池", ItemType.Equipment, "" },

    -- Trap Materials 5 --
    { "item_material_screw", "螺丝", ItemType.Material, "" },
    { "item_material_battery", "电池", ItemType.Material, "" },
    { "item_material_spike", "针", ItemType.Material, "" },
    
    -- Trap 6 --
    { "item_trap_spike", "尖刺陷阱", ItemType.Trap, "" },
    { "item_trap_mine", "地雷", ItemType.Trap, "" },

    --{ "item_equipment_雷霆战盔", ItemType.Equipment, "雷霆战盔", "" },
    --{ "item_equipment_雷霆战甲", ItemType.Equipment, "雷霆战甲", "" },
    --{ "item_equipment_雷霆战靴", ItemType.Equipment, "雷霆战靴", "" },

    -- Consumable 2 --

    -- Shard 3 --
};

local mt = {};
mt.__index = function(table, key)
    if (fieldIndex[key]) then
        return table[fieldIndex[key]];
    end
end
mt.__metatable = false;

for _, v in pairs(item) do
    setmetatable(v, mt);
end

return item;