---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 17:20
---

local levels = {};

local mapPattern = {
    "Map_1",
    "Map_2",
    "Map_3",
    "Map_4",
    "Map_5",
};

-- 1~10关
local basePatterns = {
    -- MISSION 1
    {
        name = "桃园梦始",
        -- 2步兵
        grids = {
            { gridIndex = 0, chaId = "cha_bubing", grade = 2 },
            { gridIndex = 1, chaId = "cha_bubing", grade = 2 },
        },
        mapId = nil,
    },
    {
        name = "牛刀小试",
        -- 2步兵、1旗手
        grids = {
            { gridIndex = 0, chaId = "cha_bubing", grade = 3 },
            { gridIndex = 1, chaId = "cha_bubing", grade = 3 },
            { gridIndex = 3, chaId = "cha_qishou", grade = 3 },
        },
        mapId = nil,
    },
    {
        name = "牛刀小试",
        -- 3步兵、1弓兵
        grids = {
            { gridIndex = 0, chaId = "cha_bubing",   grade = 3 },
            { gridIndex = 1, chaId = "cha_bubing",   grade = 3 },
            { gridIndex = 2, chaId = "cha_bubing",   grade = 3 },
            { gridIndex = 3, chaId = "cha_gongbing", grade = 3 },
        },
        mapId = nil,
    },
    {
        name = "汜水关之战",
        -- 2骑兵、2弓兵、1步兵
        grids = {
            { gridIndex = 0, chaId = "cha_qibing",   grade = 4 },
            { gridIndex = 1, chaId = "cha_bubing",   grade = 4 },
            { gridIndex = 2, chaId = "cha_qibing",   grade = 4 },
            { gridIndex = 3, chaId = "cha_gongbing", grade = 4 },
            { gridIndex = 5, chaId = "cha_gongbing", grade = 4 },
        },
        mapId = nil,
    },
    -- MISSION 5
    {
        -- 吕布、4骑兵、1鼓手
        name = "虎牢关之战",
        grids = {
            --{ gridIndex = 0, chaId = "cha_qibing", grade = 5 },
            { gridIndex = 0, chaId = "cha_lvbu", grade = 14 },
            --{ gridIndex = 2, chaId = "cha_qibing", grade = 5 },
            --{ gridIndex = 3, chaId = "cha_qibing", grade = 5 },
            --{ gridIndex = 4, chaId = "cha_gushou", grade = 5 },
            --{ gridIndex = 5, chaId = "cha_qibing", grade = 5 },
        },
        mapId = "Map_hulaoguan",
    },
    {
        name = "群雄割据",
        -- 2骑兵、2弓兵、1步兵
        grids = {
            { gridIndex = 0, chaId = "cha_qibing",   grade = 6 },
            { gridIndex = 1, chaId = "cha_bubing",   grade = 6 },
            { gridIndex = 2, chaId = "cha_qibing",   grade = 6 },
            { gridIndex = 3, chaId = "cha_gongbing", grade = 6 },
            { gridIndex = 5, chaId = "cha_gongbing", grade = 6 },
        },
        mapId = nil,
    },
    {
        name = "群雄割据",
        -- 3水兵、3护卫
        grids = {
            { gridIndex = 0, chaId = "cha_huwei",    grade = 7 },
            { gridIndex = 1, chaId = "cha_huwei",    grade = 7 },
            { gridIndex = 2, chaId = "cha_huwei",    grade = 7 },
            { gridIndex = 3, chaId = "cha_qibing", grade = 7 },
            { gridIndex = 4, chaId = "cha_qibing", grade = 7 },
            { gridIndex = 5, chaId = "cha_qibing", grade = 7 },
        },
        mapId = nil,
    },
    -- MISSION 8
    {
        -- 1夏侯惇
        name = "博望坡之战",
        grids = {
            { gridIndex = 0, chaId = "cha_qibing",    grade = 8 },
            { gridIndex = 1, chaId = "cha_qibing",    grade = 8 },
            { gridIndex = 2, chaId = "cha_qibing",    grade = 8 },
            { gridIndex = 3, chaId = "cha_qibing",    grade = 8 },
            { gridIndex = 4, chaId = "cha_xiahoudun", grade = 10 },
            { gridIndex = 5, chaId = "cha_qibing",    grade = 8 },
        },
        mapId = nil,
    },
    {
        -- 3水兵、2弓兵、1鼓手
        name = "水兵操练",
        grids = {
            { gridIndex = 0, chaId = "cha_shuibing", grade = 9 },
            { gridIndex = 1, chaId = "cha_shuibing", grade = 9 },
            { gridIndex = 2, chaId = "cha_shuibing", grade = 9 },
            { gridIndex = 3, chaId = "cha_shuibing", grade = 9 },
            { gridIndex = 4, chaId = "cha_gongbing", grade = 9 },
            { gridIndex = 5, chaId = "cha_gushou",   grade = 9 },
            { gridIndex = 6, chaId = "cha_zhouyu",   grade = 3 },
            { gridIndex = 7, chaId = "cha_gongbing", grade = 9 },
        },
        mapId = "Map_6",
    },
    -- MISSION 10
    {
        name = "孙刘联盟",
        -- 孙权、周瑜、3水兵、1鼓手
        grids = {
            { gridIndex = 0, chaId = "cha_shuibing", grade = 10 },
            { gridIndex = 1, chaId = "cha_shuibing", grade = 10 },
            { gridIndex = 2, chaId = "cha_shuibing", grade = 10 },
            { gridIndex = 3, chaId = "cha_shuibing", grade = 10 },
            { gridIndex = 4, chaId = "cha_shuibing", grade = 10 },
            { gridIndex = 5, chaId = "cha_shuibing", grade = 10 },
            { gridIndex = 6, chaId = "cha_zhouyu",   grade = 3 },
            { gridIndex = 7, chaId = "cha_sunquan",  grade = 3 },
            { gridIndex = 8, chaId = "cha_gushou",   grade = 10 },
        },
        mapId = "Map_5",
    },
};

local patterns = {
    {
        -- 3步兵、2弓兵、1旗手
        grids = {
            { gridIndex = 0, chaId = "cha_bubing",   grade = 1 },
            { gridIndex = 1, chaId = "cha_bubing",   grade = 1 },
            { gridIndex = 2, chaId = "cha_bubing",   grade = 1 },
            { gridIndex = 3, chaId = "cha_gongbing", grade = 1 },
            { gridIndex = 4, chaId = "cha_qishou",   grade = 1 },
            { gridIndex = 5, chaId = "cha_gongbing", grade = 1 },
        },
        mapId = nil,
    },
    {
        -- 2骑兵、1步兵，1弓兵、1旗手、1鼓手
        grids = {
            { gridIndex = 0, chaId = "cha_qibing",   grade = 1 },
            { gridIndex = 1, chaId = "cha_bubing",   grade = 1 },
            { gridIndex = 2, chaId = "cha_qibing",   grade = 1 },
            { gridIndex = 3, chaId = "cha_gongbing", grade = 1 },
            { gridIndex = 4, chaId = "cha_qishou",   grade = 1 },
            { gridIndex = 5, chaId = "cha_gushou",   grade = 1 },
        },
        mapId = nil,
    },
    {
        -- 3护卫、1骑兵、1弓兵、1旗手
        grids = {
            { gridIndex = 0, chaId = "cha_huwei",    grade = 1 },
            { gridIndex = 1, chaId = "cha_huwei",    grade = 1 },
            { gridIndex = 2, chaId = "cha_huwei",    grade = 1 },
            { gridIndex = 3, chaId = "cha_qibing",   grade = 1 },
            { gridIndex = 4, chaId = "cha_gongbing", grade = 1 },
            { gridIndex = 5, chaId = "cha_qishou",   grade = 1 },
        },
        mapId = nil,
    },
    {
        -- 6水兵
        grids = {
            { gridIndex = 0, chaId = "cha_shuibing", grade = 1 },
            { gridIndex = 1, chaId = "cha_shuibing", grade = 1 },
            { gridIndex = 2, chaId = "cha_shuibing", grade = 1 },
            { gridIndex = 3, chaId = "cha_shuibing", grade = 1 },
            { gridIndex = 4, chaId = "cha_shuibing", grade = 1 },
            { gridIndex = 5, chaId = "cha_shuibing", grade = 1 },
        },
        mapId = nil,
    },
    {
        -- 3护卫、1骑兵、1弓兵、1鼓手
        grids = {
            { gridIndex = 0, chaId = "cha_huwei",    grade = 1 },
            { gridIndex = 1, chaId = "cha_huwei",    grade = 1 },
            { gridIndex = 2, chaId = "cha_huwei",    grade = 1 },
            { gridIndex = 3, chaId = "cha_qibing",   grade = 1 },
            { gridIndex = 4, chaId = "cha_gongbing", grade = 1 },
            { gridIndex = 5, chaId = "cha_gushou",   grade = 1 },
        },
        mapId = nil,
    },
};
-- 关卡数据处理
for idx = 1, 10 do
    local id = idx;
    local gridInfoPattern = basePatterns[(idx - 1) % #basePatterns + 1];
    local level = {
        id = id,
        rewards = {
            { id = "item_currency_coin", count = 100 * idx }
        },
        gridInfos = {},
        mapId = gridInfoPattern.mapId,
    };
    if (level.mapId == nil) then
        level.mapId = mapPattern[(idx - 1) % #mapPattern + 1];
    end
    if (gridInfoPattern.name == nil) then
        level.name = "征战之路";
    else
        level.name = gridInfoPattern.name;
    end

    for i = 1, #gridInfoPattern.grids do
        level.gridInfos[i] = {
            gridIndex = gridInfoPattern.grids[i].gridIndex,
            chaId = gridInfoPattern.grids[i].chaId,
            grade = gridInfoPattern.grids[i].grade,
        };
    end
    levels[idx] = level;
end

for idx = 11, 100 do
    local id = idx;
    local gridInfoPattern = patterns[(idx - 1) % #patterns + 1];
    local level = {
        id = id,
        rewards = {
            { id = "item_currency_coin", count = 100 * idx }
        },
        gridInfos = {},
        mapId = gridInfoPattern.mapId,
    };
    if (level.mapId == nil) then
        level.mapId = mapPattern[(idx - 1) % #mapPattern + 1];
    end
    if (gridInfoPattern.name == nil) then
        level.name = "征战之路";
    else
        level.name = gridInfoPattern.name;
    end

    for i = 1, #gridInfoPattern.grids do
        level.gridInfos[i] = {
            gridIndex = gridInfoPattern.grids[i].gridIndex,
            chaId = gridInfoPattern.grids[i].chaId,
            grade = idx,
        };
    end
    levels[idx] = level;
end

return levels;
