---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 17:20
---

local levels = {};

local patterns = {
    {
        -- 2坦克
        { gridIndex = 0, chaId = "cha_bubing", grade = 1 },
        { gridIndex = 1, chaId = "cha_bubing", grade = 1 },
    },

    {
        -- 3坦克，2射手、1辅助
        { gridIndex = 0, chaId = "cha_bubing",   grade = 1 },
        { gridIndex = 1, chaId = "cha_bubing",   grade = 1 },
        { gridIndex = 2, chaId = "cha_bubing",   grade = 1 },
        { gridIndex = 3, chaId = "cha_gongbing", grade = 1 },
        { gridIndex = 4, chaId = "cha_qishou",   grade = 1 },
        { gridIndex = 5, chaId = "cha_gongbing", grade = 1 },
    },
};
-- 关卡数据处理
for idx = 1, 100 do
    local id = idx;
    local gridInfoPattern = patterns[(idx - 1) % #patterns + 1];
    local level = {
        id = id,
        name = "Level_" .. tostring(id),
        rewards = {
            { id = "item_currency_coin", count = 100 * idx }
        },
        gridInfos = {},
    };

    for i = 1, #gridInfoPattern do
        level.gridInfos[i] = {
            gridIndex = gridInfoPattern[i].gridIndex,
            chaId = gridInfoPattern[i].chaId,
            grade = gridInfoPattern[i].grade
        };
    end
    levels[idx] = level;
end

return levels;
