---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/30 13:43
---

local TimelineNode = CS.MBF.TimelineNode;
local GameLuaInterface = CS.TheGame.GM.GameLuaInterface;
local ItemStack = CS.TheGame.ItemStack;

local equip_des = require("Designer/Equipment_Description");
local cha_des = require("Designer/Character_Description");

local function GetItem(timelineObj, params)
    local itemWillGet = params[0];
    GameLuaInterface.GetItem(itemWillGet.id, itemWillGet.count);
    return true;
end

local function GetRole(timelineObj, params)
    local chaId = params[0];
    GameLuaInterface.UnlockCharacter(chaId);
    return true;
end

local fieldIndex = {};
fieldIndex.Id = 1;
fieldIndex.Name = 2;
fieldIndex.Description = 3;
fieldIndex.Icon = 4;
fieldIndex.Limits = 5;
fieldIndex.Tags = 6;
fieldIndex.Price = 7;
fieldIndex.Effect = 8;

local shop = {
    { "product_zhaoyun", "武将·赵云", cha_des["cha_zhaoyun"], "Roles/ui_cha_zhaoyun", 1, { "role", "common" }, ItemStack("item_currency_coin", 500), TimelineNode(0, GetRole, { "cha_zhaoyun" }) },
    { "product_pangtong", "武将·庞统", cha_des["cha_pangtong"], "Roles/ui_cha_pangtong", 1, { "role", "common" }, ItemStack("item_currency_coin", 800), TimelineNode(0, GetRole, { "cha_pangtong" }) },
    { "product_zhugeliang", "武将·诸葛亮", cha_des["cha_zhugeliang"], "Roles/ui_cha_zhugeliang", 1, { "role", "common" }, ItemStack("item_currency_coin", 1200), TimelineNode(0, GetRole, { "cha_zhugeliang" }) },
    -- { "product_lvbu", "武将·吕布", cha_des["cha_lvbu"], "Roles/ui_cha_lvbu", 1, { "role", "common" }, ItemStack("item_currency_coin", 2000), TimelineNode(0, GetRole, { "cha_lvbu" }) },
    --{ "product_奇幻战甲", "奇幻战甲", "", "Items/ui_head_item_equipment_奇幻战甲", { "equip", "common" }, ItemStack("item_currency_coin", 200), TimelineNode(0, GetItem, { ItemStack("item_equipment_奇幻战甲", 1) }) },
    --{ "product_奇幻战盔", "奇幻战盔", "", "Items/ui_head_item_equipment_奇幻战盔", { "equip", "common" }, ItemStack("item_currency_coin", 200), TimelineNode(0, GetItem, { ItemStack("item_equipment_奇幻战盔", 1) }) },
};

local mt = {};
mt.__index = function(table, key)
    if (fieldIndex[key]) then
        return table[fieldIndex[key]];
    end
end
mt.__metatable = false;

for _, v in pairs(shop) do
    setmetatable(v, mt);
end

return shop;
