---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 17:20
---

local timelineTable = require("Designer/Timeline");

--- id, tags, cooldown, effect
local skill = {
    skill_liubei = { id = "skill_liubei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_ad_a"] },
    skill_guanyu = { id = "skill_guanyu", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_zhangfei = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_zhaoyun = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_zhugeliang = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_ad_a"] },
    skill_pangtong = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_sunquan = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_zhouyu = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_xiahoudun = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_lvbu = { id = "skill_zhangfei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    
    skill_bubing = { id = "skill_bubing", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_qishou = { id = "skill_qishou", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_gongbing = { id = "skill_gongbing", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_ad_a"] },
    skill_gushou = { id = "skill_gushou", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_shuibing = { id = "skill_shuibing", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_huwei = { id = "skill_huwei", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
    skill_qibing = { id = "skill_qibing", tags = nil, cooldown = 0, effect = timelineTable.Model["skill_tank_a"] },
};

return skill;