---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/5/7 10:51
---

local TimelineNode = CS.MBF.TimelineNode;
local GameLuaInterface = CS.TheGame.GM.GameLuaInterface;
local ItemStack = CS.TheGame.ItemStack;

local equipment = require("Designer/Equipment");

local function GetFixedItem(timelineObj, args)
    return args[0];
end

local function GetShard(timelineObj, args)
    return ItemStack("shard_guanyu", 1);
end

local function GetCharacter(timelineObj, args)
    return ItemStack("shard_guanyu", 1);
end

local function GetRandomEquipment(timelineObj, args)
    local idx = math.random(1, #equipment);
    --print("random index: " .. idx);
    local e = equipment[idx];
    --print(e);
    --print(e.id);
    return ItemStack(e.id, 1);
end

local function CanDrawAlways(summon)
    return true;
end

local function CheckCanDrawCharacter(summon)
    return true;
end

local function CheckCanDrawShard(summon)
    return true;
end

local fieldIndex = {};
fieldIndex.Id = 1;
fieldIndex.Weight = 2;
fieldIndex.Condition = 3;
fieldIndex.Effect = 4;

local summon = {
    -- Id, Weight, Condition, Effect
    { "summon_normal", 6, CanDrawAlways, TimelineNode(0, GetFixedItem, { ItemStack("item_currency_coin", 10) }) },
    { "summon_special", 3, CanDrawAlways, TimelineNode(0, GetFixedItem, { ItemStack("item_currency_coin", 20) }) },
    { "summon_equipment", 1, CanDrawAlways, TimelineNode(0, GetRandomEquipment, nil) },
    --{ "summon_shard", 2, CanDrawAlways, TimelineNode(0, GetShard, nil) },
    --{ "summon_character", 1, CanDrawAlways, TimelineNode(0, GetCharacter, nil) },
};

local mt = {};
mt.__index = function(table, key)
    if (fieldIndex[key]) then
        return table[fieldIndex[key]];
    end
end
mt.__metatable = false;

for _, v in pairs(summon) do
    setmetatable(v, mt);
end

return summon;