---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/24 17:21
---

local event = require("Designer/Timeline_Event");
local model = require("Designer/Timeline_Model");

local timeline = {};

timeline.Event = event;
timeline.Model = model;

return timeline;