---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/8/6 17:26
---

local timelineTable = require("Designer/Timeline");

local trap = {};

-- 地雷，#爆炸#直接伤害
trap.trap_mine = {
    id = "trap_mine",
    name = "地雷",
    materials = { { id = "item_material_battery", count = 6 }, { id = "item_material_screw", count = 3 } },
    timeline = timelineTable["trap_mine"],
};
-- 尖刺陷阱，#减速
trap.trap_spike = {
    id = "trap_spike",
    name = "尖刺陷阱",
    materials = { { id = "item_material_spike", count = 4 }, { id = "item_material_screw", count = 2 } },
    timeline = timelineTable["trap_spike"],
    --    new TimelineModel("", 10,
    --            new List<TimelineNode>()
    --    {
    --        new TimelineNode(0, (obj, args) =>
    --{
    --Vector2 worldPos = position;
    --AoeLauncher al = new AoeLauncher(
    --LuaToCsBridge.AoeTable["aoe_mine"],
    --null, 0, worldPos, 2500, 0, 0.5f, new ChaProp(0, 100, 0, 0, 0)
    --);
    --GameLuaInterface.CreateAoe(al);
    --return null;
    --}, null),
    --}),
};

return trap;