---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/21 17:58
---

--- 代码规范：方法用大写开头，lua变量小写开头，如果是CS类型用大写开头

_G.Game = {};
_G.Utils = require("Utils");

function _G.Game.InitLuaTables()
    _G.Game.Designer = {};
    _G.Game.Designer.Formula = require("Designer/Formula");
    _G.Game.Designer.Bullet = require("Designer/Bullet");
    _G.Game.Designer.Aoe = require("Designer/Aoe");
    _G.Game.Designer.Character = require("Designer/Character");
    _G.Game.Designer.Level = require("Designer/Level");
    _G.Game.Designer.Item = require("Designer/Item");
    _G.Game.Designer.Skill = require("Designer/Skill");
    _G.Game.Designer.Equipment = require("Designer/Equipment");
    _G.Game.Designer.Trap = require("Designer/Trap");
    _G.Game.Designer.Timeline = require("Designer/Timeline");
    _G.Game.Designer.Buff = require("Designer/Buff");
    _G.Game.Designer.Shop = require("Designer/Shop");
    _G.Game.Designer.Summon = require("Designer/Summon");
    _G.Game.Designer.Story = require("Designer/Story");
    _G.Game.Designer.Daily = require("Designer/Daily");
    _G.Game.Designer.DefaultEquip = require("Designer/Character_DefaultEquip");
end

return _G.Game;
