---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by danny.
--- DateTime: 2025/4/27 18:15
---

local utils = {};

function utils.IsNil(obj)
    return obj == nil or obj:Equals(nil);
end

return utils;